# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rfiu9ELDw6SYPaAzsBD65HSrSS-JaqYA
"""

pip install streamlit

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import bisect

# Parámetros del problema
r = 5.5  # radio de la esfera en cm
rho_esfera = 0.6
V_esfera = (4/3) * np.pi * r**3

# Función objetivo
def f(d):
    V_sumergido = np.pi * d**2 * (r - d/3)
    return V_sumergido - rho_esfera * V_esfera

# Método de Falsa Posición
def falsa_posicion(f, a, b, tol=1e-6, max_iter=100):
    for _ in range(max_iter):
        fa, fb = f(a), f(b)
        if fa * fb >= 0:
            raise ValueError("La función no cambia de signo en el intervalo.")
        c = b - fb * (b - a) / (fb - fa)
        fc = f(c)
        if abs(fc) < tol or abs(b - a) < tol:
            return c
        if fa * fc < 0:
            b = c
        else:
            a = c
    return c

# Interfaz de usuario con Streamlit
st.title("📐 Búsqueda de raíces en una esfera flotante")

st.sidebar.header("Opciones del método")
metodo = st.sidebar.selectbox("Seleccione el método numérico:", ["Bisección", "Falsa Posición"])

# Intervalo inicial fijo
a, b = 0.1, 2 * r

# Botón para ejecutar el cálculo
if st.sidebar.button("Calcular raíz"):
    try:
        if metodo == "Bisección":
            raiz = bisect(f, a, b)
        elif metodo == "Falsa Posición":
            raiz = falsa_posicion(f, a, b)

        st.success(f"✅ Método: {metodo}")
        st.info(f"📌 Raíz encontrada: d = {raiz:.6f} cm")

        # Gráfica
        d_vals = np.linspace(0, 2 * r, 400)
        f_vals = [f(d) for d in d_vals]

        fig, ax = plt.subplots()
        ax.plot(d_vals, f_vals, label="f(d)")
        ax.axhline(0, color='red', linestyle='--')
        ax.axvline(raiz, color='green', linestyle=':', label=f"Raíz ({metodo})")
        ax.set_title("Búsqueda de raíces")
        ax.set_xlabel("Profundidad d (cm)")
        ax.set_ylabel("f(d)")
        ax.legend()
        ax.grid(True)

        st.pyplot(fig)

    except Exception as e:
        st.error(f"❌ Error: {e}")